# clog project configuration
# This file should be committed to version control to share project identity with your team

uuid: b2662e52-417b-4fb8-9830-d82885b0ceb8
display_name: doist
created_at: 2025-10-31T13:49:08.441233Z
